export const works = [
  {
    id: 1,
    title: "Freelance",
    company: "Cocoa Processing Company",
    desc: "Developed a modern website for one of the leading cocoa processing companies in Ghana. The company processes raw cocoa beans into semi-finished products, Cocoa Liquor, Butter and other confectionery products.",
    link: "https://www.goldentreeghana.com/",
    img: "/assets/cpc.png",
    stack: [
      "Vanilla Javascript",
      "Jquery",
      "Node Js",
      "MongoDB",
      "Rest Api",
      "Google Map Service",
      "HTML5",
      "CSS3",
    ],
  },
  {
    id: 2,
    title: "Front-End Developer",
    company: "Qlipay",
    desc: "Lead Front-End Engineer on Q-lipay, a platform that enables financial institutions and money transfer operators offer bill payment and mobile money value added services to their customers. Customers use their trusted channels and local payment schemes to pay for bills, goods and services in their home countries.",
    link: "https://www.qlipay.de/",
    img: "/assets/qlipay.png",
    stack: [
      "Next Js",
      "HTML5",
      "SASS",
      "Formik",
      "Node-Countries",
      "React Responsive Carousel",
      "Material UI",
    ],
  },
];

export const slideImages = [
  {
    id: 1,
    url: "/assets/social.jpg",
    video: "/assets/LinkUp.mp4",
    title: "LINK UP SOCIAL APP",
    website: "https://link-up-social.herokuapp.com/",
    code: "https://github.com/j-aloko/Link-up-Social-App.git",
    stack: [
      "Javascript",
      "React",
      "Node Js",
      "MongoDB",
      "Rest Api",
      "Web-Socket",
      "Context Api",
      "Formik",
      "HTML5",
      "CSS3",
      "Material UI",
    ],
    description:
      "Link up is a social media network that promotes sociability, photo sharing, news updates, and interaction with friends and family. This software has a built-in messenger feature, a news feed system, the ability to follow and unfollow people, likes, comments, and replies, as well as an instant notification system.",
  },
  {
    id: 2,
    url: "/assets/blog@2x.png",
    video: "/assets/BlogApp.mp4",
    title: " JUST READ BLOG ",
    website: "https://just-read-app.herokuapp.com/",
    code: "https://github.com/j-aloko/Just-Read-Blog.git",
    stack: [
      "Javascript",
      "React",
      "Node Js",
      "MongoDB",
      "Rest Api",
      "Web-Socket",
      "Cypress",
      "Context Api",
      "HTML5",
      "CSS3",
      "Material UI",
    ],
    description:
      "Just Read is a free and open platform where readers may discover new ideas and where experts and unknown voices can publish their writing on any subject. This is a fully functional 'MERN' stack web application with a great blog design and structure, a simple menu, social media integration, a commenting system, a visible search box, and a well-organized category section.",
  },
  {
    id: 3,
    url: "/assets/ecom.png",
    video: "/assets/Ecommerce.mp4",
    title: "SHOPPY",
    website: "https://shoppy--shop.herokuapp.com/",
    code: "https://github.com/j-aloko/Shoppy-Ecommerce-Shop.git",
    stack: [
      "Javascript",
      "React",
      "Node Js",
      "MongoDB",
      "Rest Api",
      "Redux",
      "HTML5",
      "Styled Components",
      "Material UI",
    ],
    description:
      "Shoppy is a 'Mern' stack women's apparel retail app with a functional checkout mechanism that makes it simple for two people to transact.",
  },
  {
    id: 4,
    url: "/assets/movieApp.png",
    video: "/assets/MovieApp.mp4",
    title: "NETFLIX CLONE",
    website: "https://trusting-cray-846e49.netlify.app/",
    code: "https://github.com/j-aloko/Netflix-Clone.git",
    stack: [
      "Javascript",
      "React",
      "Node Js",
      "MongoDB",
      "Rest Api",
      "Context Api",
      "HTML5",
      "SASS",
      "Material UI",
    ],
    description:
      "This is a fun Mern stack movie streaming program that has a wide range of TV shows and movies to choose from. It also features a useful Admin dashboard, which allows the administrator to keep track of users, post, update, and delete movies and TV series from the website.",
  },
];

export const testimonials = [
  {
    id: 1,
    img: "assets/Purkins.jpg",
    desc: "Coming from a finance background, I'm really impressed at how Joseph has evolved in web development over the years. His humilty and willingness to learn and evolve is what has brought him this far. I'm honoured to have mentored him in his journey.",
    email: "fpurkinstech@gmail.com",
    name: "Friedrich Purkins",
    position: "Tech Lead | Haefele Software",
  },
  {
    id: 2,
    img: "assets/Gina.jpg",
    desc: "Joseph is very conscientious and client-centered. He goes to great lengths to fully understand project requirements. This allows him to produce an effective feature in a short timeframe.",
    email: "huffmangina4@gmail.com",
    name: "Gina H. Huffman",
    position: "Product Manager | Maviance",
  },
  {
    id: 3,
    img: "assets/Green.jpg",
    desc: "I recently collaborated with Joseph on a contract at Maviance. In this time I found a very diligent person, and a most accountable one. Amongst the things he was responsible for was developing user friendly interfaces for clients projects and assisting in testing of enterprise applications.",
    email: "waynegreen344@gmail.com",
    name: "Wayne Green ",
    position: "Teammate | Maviance",
  },
  {
    id: 4,
    img: "assets/Kim.jpg",
    desc: "Joseph is an amazing developer and I love working with him. I was surprised, when i found out about his background in finance and despite that, He is the guy you want, when you need to pair programme and debug code with. He solves problems calmly, professionally, with a great attitude.",
    email: "kimluczyk00@gmail.com",
    name: "kimberly Luczyk",
    position: "Teammate | Maviance",
  },
];
